### ISSUE TITLE
Translating Deno documentation

### ISSUE THREAD

**Issue by marcuxyz** [denoland/doc_website#101]
I would like to start translating `Deno's` **documentation** into **Portuguese**. Is there an incentive for that? How can I get started? After I translate where do I open a `PR`?

**Comment by eialanjones** [comment]
[https://github.com/denoland/deno/issues/5435](url)

**Comment by tokiedokie** [comment]
ref: denoland/deno#7490, denoland/deno#5435, denoland/deno_website2#550, denoland/deno#5911
