### ISSUE TITLE
Documentation is not being generated

### ISSUE THREAD

**Issue by singla-shivam** [denoland/doc_website#110]
Documentation for [fae](https://doc.deno.land/https/deno.land/x/fae/mod.ts) opened 2 or 3 times. After that it is showing **A internal server error occured while generating the documentation.**

Module - https/deno.land/x/fae/mod.ts

**Comment by kennanseno** [comment]
similar to https://github.com/denoland/doc_website/issues/96

**Comment by bartlomieju** [comment]
CC @lucacasonato

**Comment by lucacasonato** [comment]
Duplicate of #96
