### ISSUE TITLE
Sections are hidden by the navbar when clicking on links (Safari)

### ISSUE THREAD

**Issue by HuguesChocart** [denoland/doc_website#111]
When clicking on Deno.close for example on Safari: 

<img width="1279" alt="Screenshot 2020-06-02 at 2 25 20 AM" src="https://user-images.githubusercontent.com/24587702/83466753-63771200-a478-11ea-985e-0cf0e689ac90.png">

Whereas it's working fine on Chromium:

<img width="1279" alt="Screenshot 2020-06-02 at 2 26 43 AM" src="https://user-images.githubusercontent.com/24587702/83466805-8b667580-a478-11ea-9cd3-1c0f756ab268.png">

I'm not sure where the problem comes from, maybe it comes from Vercel Links. 
I haven't had much time to look into it more in depth but I'll try to spend some more time finding what the issue is and I'll try to fix it. 

Feel free to give my any hint if you think what the problem might be :)

**Comment by lucacasonato** [comment]
Fixed as header was removed. (At least on desktop).
