### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by dionjwa** [denoland/doc_website#119]
Not sure where to post this. July 13. 

https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts

![image](https://user-images.githubusercontent.com/260221/87357636-3313a080-c519-11ea-88c6-20df971aafc8.png)

**Comment by lucacasonato** [comment]
Interesting, the site is working for me: 
![image](https://user-images.githubusercontent.com/7829205/87360756-12743680-c56b-11ea-906b-fa50628034a3.png)

Could you visit https://doc.deno.land/api/docs?entrypoint=https%3A%2F%2Fgithub.com%2Fdenoland%2Fdeno%2Freleases%2Flatest%2Fdownload%2Flib.deno.d.ts&force_reload=true and then visit the page again? This will clear out the server side cache.

**Comment by dionjwa** [comment]
Yeah it works now, you can close 🤷 
Sorry if it was just me for the noise.
