### ISSUE TITLE
Panic caused by TSX file

### ISSUE THREAD

**Issue by sholladay** [denoland/doc_website#168]
While `deno doc https://deno.land/x/pogo@v0.5.2/main.ts` works as expected, the equivalent https://doc.deno.land/https/deno.land/x/pogo@v0.5.2/main.ts shows an error message (note: I've formatted it for readability):

> A internal server error occured while generating the documentation.
>
> Download https://deno.land/x/pogo@v0.5.2/main.ts
> Download https://deno.land/x/pogo@v0.5.2/lib/request.ts
> Download https://deno.land/x/pogo@v0.5.2/lib/server.ts
> Download https://deno.land/x/pogo@v0.5.2/lib/toolkit.ts
> Download https://deno.land/x/pogo@v0.5.2/lib/router.ts
> Download https://deno.land/x/pogo@v0.5.2/lib/response.ts
> Download https://deno.land/x/pogo@v0.5.2/lib/types.ts
> Download https://deno.land/x/pogo@v0.5.2/lib/helpers/file.ts
> Download https://deno.land/x/pogo@v0.5.2/lib/helpers/directory.tsx
> Expected >, got basePath at https://deno.land/x/pogo@v0.5.2/lib/helpers/directory.tsx:30:43 

The message looks simple enough, it seems to be choking on the TSX syntax in `lib/helpers/directory.tsx`. Problem is, the syntax in that file is valid and `deno doc` works correctly when I run it locally. Maybe the code is getting mangled on the backend of the doc website or there is a corrupted cache or something? Maybe the doc website is using an old version of `deno doc`?

I figured I would try to visit the TSX file directly and see if that worked, so I went to https://doc.deno.land/https/deno.land/x/pogo@v0.5.2/lib/helpers/directory.tsx and what I saw the first time was a Rust panic. But... I can't reproduce it anymore since refreshing the page. Now it seems the `directory.tsx` file works. Yet, `main.ts` still shows the same error.

Maybe check the server logs for the panic?

**Comment by Liamolucko** [comment]
Fixed by #183
