### ISSUE TITLE
Quoted keys show as <TODO>

### ISSUE THREAD

**Issue by danopia** [denoland/doc_website#179]
For example: https://doc.deno.land/https/deno.land/x/aws_api@v0.3.1/client/common.ts#ApiMetadata
![Screenshot 2021-04-07 09 04 30](https://user-images.githubusercontent.com/40628/113824605-47bb5700-9780-11eb-849c-b9a4996cfa92.png)

Github code search didn't point any immediate fingers at where the TODO string is coming from..

**Comment by kt3k** [comment]
Fixed in upstream (deno_doc), but it's still blocked by 1.8.x upgrade issue https://github.com/denoland/doc_website/pull/165

**Comment by danopia** [comment]
Looks like the repro link I gave is showing the keys correctly now, thanks!
