### ISSUE TITLE
Favicon is not shown on Safari

### ISSUE THREAD

**Issue by Gumichocopengin8** [denoland/doc_website#185]
Favicon is not shown on Safari, while it's shown on Chrome.
It didnt fix even after deleting cache.

**Comment by lucacasonato** [comment]
Safari does not support SVG favicons.

**Comment by Gumichocopengin8** [comment]
Will you plan to add png favicon for Safari?

**Comment by lucacasonato** [comment]
I don't, but if anyone wants to open a PR, I will happily merge it :-)

**Comment by Gumichocopengin8** [comment]
Cool. I might make a PR for that.
