### ISSUE TITLE
runtime api link don't work

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/doc_website#188]
in deno.land site when click in runtime api I don't get inspect page

**Comment by lucacasonato** [comment]
I don't quite understand the issue. Pressing `Runtime API` on the website brings you to https://doc.deno.land/builtin/stable. What behaviour are you expecting?

**Comment by m-amazirh** [comment]
Hi @lucacasonato,

For me, clicking the link shows an error page with a message "An internal server error occured while generating the documentation".

I have the error on both Firefox and Chrome.

Here is a screenshot : https://imgur.com/a/y0RIkio

**Comment by asyncmax** [comment]
I'm getting the same error too.

**Comment by elycheikhsmail** [comment]
i mean i get page error instead of normal page.
now i get the normal page. in my opinion this is due to the way this page is generate in server side.
