### ISSUE TITLE
issue: Stable API documentation is down

### ISSUE THREAD

**Issue by marc2332** [denoland/doc_website#189]
Stable API docs website seems to not work:

https://doc.deno.land/builtin/stable

![image](https://user-images.githubusercontent.com/38158676/115974800-b6115f00-a55f-11eb-8402-3e2cfc8266d2.png)
(I tried with Chrome and Firefox, and also from my smartphone using a different network)

But, unstable works:

https://doc.deno.land/builtin/unstable

![image](https://user-images.githubusercontent.com/38158676/115974828-e78a2a80-a55f-11eb-83b5-d9b8a42936c0.png)

🤔

**Comment by ihack2712** [comment]
Happens only for built-ins and data URIs AFAIK. Anything that hits the [deno doc proxy](https://github.com/denoland/doc_website/blob/main/deploy/main.ts).
