### ISSUE TITLE
navigator has some error?

### ISSUE THREAD

**Issue by devcui** [denoland/doc_website#214]
# 1. page

https://deno.land/manual@v1.11.5/runtime

# 2.operate

![image](https://user-images.githubusercontent.com/26159886/124710975-18a7b380-df30-11eb-8c9a-c6d9d9652ac5.png)

# 3.effect

![image](https://user-images.githubusercontent.com/26159886/124711084-34ab5500-df30-11eb-931c-6347e98e00c2.png)

# 4.question

it seem's like the url has some error?

**Comment by kt3k** [comment]
Thank you for reporting. The link should navigate to https://doc.deno.land/builtin/stable instead of the above error page. This will be fixed in the next release.
