### ISSUE TITLE
Hosted version of deno_doc (docs.deno.land)

### ISSUE THREAD

**Issue by lucacasonato** [denoland/doc_website#30]
It would be great to have a hosted version of deno_doc that you give a URL and it fetches that module, analyzes it, and displays it.

I think there are two reasonable approaches here:
- have a serverless function or server that executes `deno doc` and responds to the client with the json output
- wasmify the deno doc section of deno and use client side fetch() to fetch code and analyze it with the wasm

The first one is definitely easier, but requires a little bit more maintenance as it needs to be deployed, while the second one will be a lot harder to build, but requires nearly no effort on the deployment side.

I built a demo for the first approach that uses [Zeit Now](https://zeit.co/home): a combination of static hosting, serverless function hosting and a CDN - https://deno-doc.lucacasonato.now.sh/deno.land/std/http/server.ts. It uses my project [now-deno](https://github.com/lucacasonato/now-deno) that you can use to deploy serverless Deno functions to Now. I made use of this for the actual backend parser, and just use a slightly adjusted version of the frontend in this repo for the display. The code can be found in this branch: https://github.com/luca-rand/deno_doc/tree/hosted2 ([diff](https://github.com/bartlomieju/deno_doc/compare/master...luca-rand:hosted2)). This is still rudimentary, but it works really well.

Is this something that we want? Are there other approaches that might work better?

/cc @ry @bartlomieju

**Comment by ry** [comment]
>  https://deno-doc.lucacasonato.now.sh/deno.land/std/http/server.ts

This is very cool - and what I hoped we could achieve for the docs. (Is it supposed to work for other URLs, when I put in https://deno-doc.lucacasonato.now.sh/deno.land/std/encoding/csv.ts, I don't see any docs?)

It seems the wasm approach is going to be quite painful. I would rather setup some server-side stuff. We also need to figure out how to properly cache. Godoc.org has a little button at the bottom that lets anonymous users flush the cache. See "Refresh now" at the bottom of any godoc page https://godoc.org/github.com/dave/dst

**Comment by lucacasonato** [comment]
Th

**Comment by lucacasonato** [comment]
It's meant to work but there are still some bugs in the parser I think. Also this uses deno 'stable' so things that are fixed on master don't work yet. I'll look into that specific case.

About the caching: We can set up the ZEIT CDN to cache for eg. one day and then have a way to force reload by using a query parameter. We could then show a 'Refresh now' link in the top left under or next to the 'Generated on' text. This should be relatively easy to implement. If we want to go for something else, we can probably use Cloudflare Workers (and Cloudflare Workers KV) to handle caching.

On a somewhat related note: If this is deployed as a standalone application to a seperate domain like https://docs.deno.land, I can also set up server side rendering for the React application, which would make initial load times a lot faster.

Do we want to use Now? It is really easy to use and pretty customizable as it is built on AWS Lambda (so we can do advanced things if required). It also does deploy previews and such like Netlify.

**Comment by ry** [comment]
I'm happy to setup a subdomain for this. I've never used Now but happy to try it out.

I'll wait a few days until you have this a bit further along and invest some time next week in getting it hooked up.
