### ISSUE TITLE
Thoughts about "Defined in file ..." links

### ISSUE THREAD

**Issue by bartlomieju** [denoland/doc_website#47]
![Screenshot 2020-04-08 at 21 50 41](https://user-images.githubusercontent.com/13602871/78827185-02384280-79e3-11ea-81aa-545cbd265a53.png)

Couple of thoughts:
* line and column are not part of the link - effectively all links on the whole page link to the same thing - it would be great to format them as `<url>:<line>:<col>`
* wrapping link in single quote `'<url>'` is not very readable - I'd prefer it was underlined - visible and accessible 
* the whole link takes a lot of space - especially for long URLs - I like how `docs.rs` solves this problem by showing `[src]` link in the right-hand side corner:
![Screenshot 2020-04-08 at 21 53 02](https://user-images.githubusercontent.com/13602871/78827402-5fcc8f00-79e3-11ea-8f77-33b8d2f5617b.png)

**Comment by hayd** [comment]
👍 to `[src]` link.

The problem with the :line:col format is that not all urls support this.

**Comment by ry** [comment]
#L14-L43 works on Github and Deno.land. Fragment URLs will be more robust to sites that don’t support it.

**Comment by bartlomieju** [comment]
> #L14-L43 works on Github and Deno.land. Fragment URLs will be more robust to sites that don’t support it.

That's fine I just meant that line and column should be encoded in URL 👍
