### ISSUE TITLE
feature request:  inline expandable source

### ISSUE THREAD

**Issue by cknight** [denoland/doc_website#52]
`[src]` opens in a new tab/window which can be a slightly jarring experience and may mean going back and forth between the source and the docs.  One suggestion would be to have `[src]` expand an inline iframe with the source in it.  Example:

![Screenshot at 2020-04-09 10:09:23](https://user-images.githubusercontent.com/1248238/78878707-b9b46f80-7a4a-11ea-9be8-286a683bb8c2.png)

Having another link to open in a new tab/window would also be good.

**Comment by lucacasonato** [comment]
I don't like the inline iframe. I think an actual full page source display as described in #54 is better.

**Comment by cknight** [comment]
Perhaps a better title for this suggestion would have been "Better source integration" which is what I'm really looking for, but we developers do like to go into solution mode.  As the support for this idea is evenly split, I don't see a strong enough reason to keep this issue open.  Let's see how #54 pans out and we can iterate from there.
