### ISSUE TITLE
feature request: incorporate README.md

### ISSUE THREAD

**Issue by cknight** [denoland/doc_website#53]
The API docs are really useful for developers when working with a module.  However, this is only part of the picture.  Having access to the README.md in the same place as the API docs will give a fuller picture of the capabilities of the API and how to use the API.  For example, some of our APIs have no documentation in the code but are well documented in the README.md ([example](https://doc.deno.land/https/deno.land/std/log/mod.ts)). If a README.md is present in the same directory as the mod.ts, it should linked to somehow.

Some options to include this could be:
* README.md is the default view of the module with the left hand nav links to all the API details (as is)
* Prominently highlight the README.md at the top of the left hand navigation
* Prominently highlight the README.md at the top of the primary display pane

**Comment by lucacasonato** [comment]
Closing. See https://github.com/denoland/doc_website/issues/54#issuecomment-676546051
