### ISSUE TITLE
discussion: make page more like pkg.go.dev

### ISSUE THREAD

**Issue by lucacasonato** [denoland/doc_website#54]
If we want to add features such as #37 or a source file display as requested by @bartlomieju it might be better if we increase the scope of this site. Go moved from a simple documentation only site, https://godoc.org, to https://pkg.go.dev, a site is meant to give a complete overview for a given package.

Because our module system is decentralized we can't offer everything that pkg.go.dev does, but we can do a lot of things for any old URL, and offer some extra features for certain known providers like github, pika or jspm.

Some ideas:
- documentation
- source code view (with clickable references)
- dependency tree (pretty much `deno info` output)
- version list (for selected pages -> github, pika, jspm, ect)

This would make for a really nice and organized way for developers find info about any modules they are importing.

This might also be better suited as a third party thing, rather than a `deno` thing. What are your opinions?

Also related to #52 and #53

**Comment by cknight** [comment]
Great ideas.  A one stop shop for all documentation and information on a module would be excellent.

**Comment by lucacasonato** [comment]
I think this is out of scope actually. I'm trying to get https://deno.land/x to the point where it can be the one stop shop for all things Deno modules. It will have or already has:

- source code view
- dependency tree
- version lists
- `deno lint` and `deno fmt` analysis results
