### ISSUE TITLE
Link to MDN for JS builtins

### ISSUE THREAD

**Issue by lucacasonato** [denoland/doc_website#73]
e.g. `Date` should link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by ry** [comment]
The “deno types” includes <reference> links to other type definitions like Date. It would be cool if we could explore those.

**Comment by kennanseno** [comment]
Trying to explore how we can do this safely without creating any dead links.

On top of my head:
1. Have a list(nothing fancy, just an array inside the util function itself) of Global objects that's in MDN, check if type is in that list, if it is, link it. leave as is if not.
2. Do a call to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/<TYPE>, if it returns 404 page, leave as is, else create a link.

Leaning on 1 personally. Happy to do the change on this if you guys think it'll suffice as first pass @ry @lucacasonato .
