### ISSUE TITLE
internal server error on README.md documentation pages.

### ISSUE THREAD

**Issue by schu34** [denoland/doc_website#82]
when I start here: https://deno.land/std/http/README.md, and click `DOCUMENTATION` in the top left I see an error page: 
![image](https://user-images.githubusercontent.com/5218700/81357361-6b25df80-90a1-11ea-86c9-fe6ee0e69372.png)

I can see  that this api request `https://doc.deno.land/api/docs?entrypoint=https%3A%2F%2Fdeno.land%2Fstd%2Fnode%2FREADME.md` is returning a 500 with this error message 
```json
{"error":"Download https://deno.land/std/node/README.md\n\n"}
```

I'm assuming it's because the server doesn't know how to generate docs from a non-ts file but the error message could be better, it was very confusing for me as a first time user.

**Comment by dosisod** [comment]
I encountered a similar issue here: [https://doc.deno.land/https/deno.land/std](https://doc.deno.land/https/deno.land/std).

I assumed It would show me a breakdown of all the available std modules, but instead it just dies :(

The request that throws the 500 error says: `Download https://deno.land/std Import 'https://deno.land/std' failed: 400 Bad Request `

**Comment by kennanseno** [comment]
The bug is in the actual website and not in the docs. Will be picking this up this weekend unless someone else wants to pick it up before that.

**Comment by kennanseno** [comment]
@lucacasonato this one can be closed.

**Comment by lucacasonato** [comment]
cc @bartlomieju
