### ISSUE TITLE
Hand drawn logo link doesn't work

### ISSUE THREAD

**Issue by filiptronicek** [denoland/doc_website#90]
The link to the hand-drawn logo responds with a 404
![logo list](https://user-images.githubusercontent.com/29888641/81933365-89ce2e00-95ed-11ea-9ff4-b7ebca056af3.png)
![deno 404](https://user-images.githubusercontent.com/29888641/81933389-96eb1d00-95ed-11ea-8acd-5b76f3c4ef29.png)

**Comment by lucacasonato** [comment]
Fixed
