### ISSUE TITLE
I am taking all the documentation to Spanish

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [denoland/doc_website#91]
I am taking all the documentation to Spanish in the following repository. https://github.com/FranciscoImanolSuarez/deno_documentacion

## I do it for people who speak Spanish but not English.

**Comment by lucacasonato** [comment]
Great! Posts like this belong on discord.gg/deno though, not as an issue on this repo. Issues are for tracking bugs and feature requests :-)
